/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculate.h"
void input(struct numbers *);
void input(struct numbers* strt)
{
	printf("Enter the first number : ");
	scanf("%d", &strt->number1);
	printf("Enter the second number : ");
	scanf("%d", &strt->number2);
}


void
calculate_1(char *host)
{
	CLIENT *clnt;
	int answer;
	int  *result_1;
	numbers  add_1_arg;
	int  *result_2;
	numbers  subtract_1_arg;
	int  *result_3;
	numbers  multiply_1_arg;
	float  *result_4;
	numbers  divide_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, CALCULATE, CALCULATE_1, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	printf("***** Welcome to the simple calculator *****\n\n");

	while(answer != 0)
	{
		printf("Enter the type of arithmetic\n");
		printf("\t1 : Addition\n\t2 : Subtraction\n\t3 : Multiplication\n\t4 : Division\n\t0 : EXit\n\n");
		scanf("%d", &answer);
		switch(answer){
			case 1:
				input(&add_1_arg);
				result_1 = add_1(&add_1_arg, clnt);
				if (result_1 == (int *) NULL) {
					clnt_perror (clnt, "call failed");
				}
				else{
					printf("Server replies sum is : %d\n\n" , *result_1);
				}
				break;
		
			case 2:
				input(&subtract_1_arg);
				result_2 = subtract_1(&subtract_1_arg, clnt);
				if (result_2 == (int *) NULL) {
					clnt_perror (clnt, "call failed");
				}
				else{
					printf("The server replies difference is %d\n\n", *result_2);
				}
				break;
		
			case 3:
				input(&multiply_1_arg);
				result_3 = multiply_1(&multiply_1_arg, clnt);
				if (result_3 == (int *) NULL) {
					clnt_perror (clnt, "call failed");
				}
				else{
					printf("The server replies product is %d\n\n", *result_3);
				}
				break;

			case 4:
				input(&divide_1_arg);
				result_4 = divide_1(&divide_1_arg, clnt);
				if (result_4 == (float *) NULL) {
					clnt_perror (clnt, "call failed");
				}
				else{
					printf("The server replies quotient is %f\n\n", *result_4);
				}
				break;

			case 0:
				break;

			default:
				printf("Invalid answer\n\a\a");

		}		
	}

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	calculate_1 (host);
exit (0);
}
