/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculate.h"

int *
add_1_svc(numbers *argp, struct svc_req *rqstp)
{
	static int  result;

	printf("Summing...\n");
	printf("The numbers are %d and %d\n" , argp->number1 , argp->number2);
	result = argp->number1 + argp->number2;
	printf("The calculated sum is %d\n\n" , result);

	return &result;
}

int *
subtract_1_svc(numbers *argp, struct svc_req *rqstp)
{
	static int  result;

	printf("Subtracting...\n");
	printf("The numbers are %d and %d\n" , argp->number1 , argp->number2);
	result = argp->number1 - argp->number2;
	printf("The calculated difference is %d\n\n" , result);



	return &result;
}

int *
multiply_1_svc(numbers *argp, struct svc_req *rqstp)
{
	static int  result;

	printf("Multiplying...\n");
	printf("The numbers are %d and %d\n" , argp->number1 , argp->number2);
	result = argp->number1 * argp->number2;
	printf("The calculated product is %d\n\n" , result);



	return &result;	
}

float *
divide_1_svc(numbers *argp, struct svc_req *rqstp)
{
	static float  result;

	printf("Dividing...\n");
	printf("The numbers are %d and %d\n" , argp->number1 , argp->number2);
	result = (float)argp->number1 / (float)argp->number2;
	printf("The calculated sum is %f\n\n" , result);


	return &result;
}
